# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus
# TODO: Write documentation for menus. ;-)

main:
  - label: Home
    title: Zobriuz home page
    path: homepage
  - path: blogs
    label: Blog
    title: Blog items
#    submenu:
#      - label: Sub 1
#        path: entry/2
#      - label: Sub 2
#        class: okidoki
#        path: entry/3
#      - label: Sub 3
#        path: entry/4
#      - class: sub-class
#        path: page/3
#  - label: Quotes
#    title: Inspirerende quotes die ik her en der verzameld heb
#    path: page/quotes